- package.json
- tsconfig.app.json
- vite.config.ts
- yarn.lock
- Closes #6 
---
---
1. path alias 설정했습니다.
---
- import 문 경로를 아래와 같이 설정했습니다.
---
- `src/component/common` 파일 안에 있는 컴포넌트 -> index.ts 파일에서 한번에 export -> 다른 컴포넌트에서 import 할 경우, 다음과 같이 import 문이 작성됩니다.
`index.ts`
`App.tsx`
> [Init/#6] path alias 설정

- .github/workflows/auto-sync.yml
- Closes #15 
---
---
1. 오가니제이션 레포를 배포하기 위해 제 개인 레포로 fork를 떴습니다.
2. vercel로 연결하여 배포를 했습니다.
3. github actions에 연결하기 위해 .github > workflows > auto-sync.yml 파일을 만들었습니다.
4. 토큰을 발급받아 적용했습니다.
---
-
---
> [Deploy/#15] CI/CD Github Actions 배포 준비 완료

- custom.d.ts
- package-lock.json
- package.json
- src/vite-env.d.ts
- tsconfig.app.json
- vite.config.ts
- yarn.lock
- Closes #5
---
---
1. SVGR 설정했습니다.
---
- 테스트도 완료했어요!
---
> [Init/#5] SVGR 세팅

- package.json
- src/App.tsx
- src/styles/global.css.ts
- src/styles/layers.css.ts
- src/styles/reset.css.ts
- src/styles/theme.css.ts
- vite.config.ts
- yarn.lock
- Closes #10 
---
---
1. vanilla extract 설치 및 세팅하기
- yarn으로 ve 및 vanillaExtractPlugin() 설치
- `vite.config.ts` 파일에 플러그인 추가
2. `reset.css.ts` 세팅하기
- reset 파일 작성 후 global 파일에 import
3. `global.css.ts` 세팅하기
- global 파일 작성 후 App 컴포넌트에 import 
4. `theme.css.ts` 세팅하기
- 피그마에 올라와있는 디자인 시스템 내용으로 theme 작성
---
- 사용 방법은 다음과 같습니다.
1️⃣ `파일명.css.ts` 스타일 파일에서 ve의 `style()`을 사용해서 스타일을 지정합니다.
- 기본적으로 style({ 이 안에 스타일을 넣어주면 됩니다! })
- theme 내용을 사용할 경우, theme 파일에서 정의한 `vars`를 import 해서 사용하면 됩니다.
- theme에서 정의한 font를 적용할 경우, style([ 이 안에 작성 후 , { 여기엔 추가로 작성할 css를 적어주면 됩니다! } ])
```react
import { vars } from '@styles/theme.css';
import { style } from '@vanilla-extract/css';
export const pStyle = style([
vars.fonts.head01_b_24,
{ color: vars.colors.black },
]);
export const textStyle = …
```
> [Init/#10] reset, global, theme 등 style 관련 세팅

- README.md
- Closes #25 
---
---
1. 열심히 리꾸했어요 ✌🏻
---
- 칭찬해주세요.
- 추가하거나 수정하고 싶은 사항 있으면 언제든지 말해주세요 👍🏻
---
> [Docs#25] 리드미 내용 추가

- index.html
- src/components/common/SocialLoginButton/SocialLoginButton.css.ts
- src/hooks/useEasyNavigate.ts
- src/styles/global.css.ts
- src/styles/theme.css.ts
- Closes #49
---
---
**1. pretendard 글로벌 스타일 적용**
프리텐다드 적용이 잘 안되길래, 다시 적용되도록 수정하고
우리 서비스에서 모든 폰트가 프리텐다드로 사용되는 것 같아 글로벌 스타일로 적용시키기 위해
global.css.ts 파일에 코드를 넣었습니다.
```
// 폰트 설정
globalStyle('body', {
fontFamily: `'Pretendard', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif`,
});
```
**2. 디자인시스템 확정에 따라, colors 변경**
아래 사진에 맞춰서 theme 수정했습니다.
---
- 한번 보긴 했는데,, 놓친게 있을 수도 있으니까 꼼꼼하게 봐주세요 허허
---
> [Fix/#49] 디자인 시스템 변경에 따른 Theme 수정

- .github/workflows/storybook.yml
- .storybook/preview.ts
- src/stories/Colors.stories.tsx
- src/stories/Configure.mdx
- src/stories/Typography.stories.tsx
- Closes #44
---
---
1. Storybook 디자인 시스템 반영
스토리북에 수정된 디자인 시스템 반영했습니다.
2. Storybook 전역 스타일 설정
preview.ts 파일에 `import '../src/styles/global.css';` 해서 스토리북 사이트에서도 전역 스타일이 적용되게 설정했습니다.
---
-
---
> [Feat/#44] Storybook 디자인 시스템 반영 및 전역 스타일 설정

- src/hooks/index.ts
- src/pages/view/components/KakaoMap/KakaoMap.tsx
- src/pages/view/components/MapBottomSheet/MapBottomSheet.tsx
- src/stories/Input.stories.tsx
- Closes #133 
---
---
1. MapButtonSheet 수정했습니다.
---
-
---
> [Fix/#133] MapBottomSheet 수정

- vercel.json
- Closes #135 
---
---
1. vercel.json 파일 추가
---
-
---
> [Deploy/#135] vercel.json 추가

- index.html
- package.json
- src/apis/home/useFetchStoreRank.ts
- src/apis/instance.ts
- src/constants/apis/api.ts
- src/constants/apis/queryKey.ts
- src/constants/index.ts
- src/types/apis/commonType.ts
- src/types/apis/home/index.ts
- src/types/index.ts
- tsconfig.app.json
- yarn.lock
- Closes #137
---
---
1️⃣ END_POINT 추가하기
```
export const END_POINT = {
FETCH_STORE_RANK: '/api/v1/store/rank',
} as const;
```
연결할 API의 엔드 포인트를 constants 폴더 안에 있는 api.ts 파일에 추가해줍니다.
2️⃣ queryKey 추가하기
```
export const queryKey = {
STORE_RANK: 'storeRank',
} as const;
```
해당 API에 지정할 쿼리 키도 지정해줍니다.
3️⃣ Response Type 추가하기
```
export interface StoreRankResponse {
stores: Array<{
storeId: number;
storeName: string;
storeLikesCount: number;
station: string;
}>;
}
```
4️⃣ API 함수 작성하기
```
const fetchStoreRank = async (): Promise<StoreRankResponse> => {
try {
const response = await instance.get<ApiResponseType<StoreRankResponse>>(
END_POINT.FETCH_STORE_RANK
);
return response.data.data;
} catch (error) {
throw error;
}
};
export const useFetchStoreRank = () => {
return …
```
> [Setting/#137] TanStack Query 세팅

- src/apis/home/index.ts
- src/apis/home/useFetchCakeRank.ts
- src/apis/home/useFetchStoreRank.ts
- src/apis/instance.ts
- src/constants/apis/api.ts
- src/constants/apis/queryKey.ts
- src/pages/home/page/HomePage/HomePage.tsx
- src/types/apis/home/index.ts
- Closes #140 
---
---
- 인기 케이크 조회 API 연결 완료 했습니다.
> [Feat/#140] 인기 케이크 조회 API 연결

- src/components/common/IconButton/IconButton.css.ts
- src/components/common/IconButton/IconButton.tsx
- Closes #162 
---
---
1. IconButton 컴포넌트 수정했습니다.
---
-
---
> [Fix/#162] IconButton 스타일 및 onMap속성 수정

- src/apis/likes/index.ts
- src/apis/likes/usePostStoreLikes.ts
- src/components/common/IconButton/IconButton.tsx
- src/constants/apis/api.ts
- src/pages/store/components/Banner/Banner.tsx
- src/types/apis/commonType.ts
- Closes #156 
---
---
- 스토어 찜하기 API 연결했습니다.
> [Feat/#156] 스토어 찜하기 API 연결

- src/apis/likes/index.ts
- src/apis/likes/usePostCakeLikes.ts
- src/components/common/IconButton/IconButton.tsx
- src/components/common/Image/Image.tsx
- src/constants/apis/api.ts
- src/pages/store/components/StoreDesign/StoreDesign.tsx
- src/types/apis/commonType.ts
- Closes #160 
---
---
- 케이크 디자인 좋아요 하기 API 연결
> [Feat/#160] 케이크 디자인 좋아요 하기 API 연결

- src/pages/view/components/MapBottomSheet/MapBottomSheet.tsx
- Closes #182
---
---
**1. 스토어 정보 리스트 조회 enabled 조건문 수정**
스토어 정보 리스트 조회 함수에서 enabled 조건이 잘못 들어가 있어 선택한 지하철 역이 변경되도 재호출이 안되는 에러가 발생했습니다.
enabled 조건문을 수정해 정상적으로 호출될 수 있게 수정했습니다!
---
-
---
> [Fix] 스토어 정보 리스트 조회 enabled 조건문 수정

- src/apis/designList/useFetchDesignList.ts
- src/apis/myPage/useFetchLikedCakeList.ts
- src/apis/myPage/useFetchLikedStoreList.ts
- src/apis/view/useFetchLikedStoreDesign.ts
- src/apis/view/useFetchLikesStoreCoordinate.ts
- src/apis/view/useFetchStationDesign.ts
- src/apis/view/useFetchStationStore.ts
- src/apis/view/useFetchStations.ts
- src/apis/view/useFetchStoreCoordinateList.ts
- Closes #187
---
---
1. 리스트 조회 API 404 에러 기본값 설정
---
-
---
> [Feat/#187] 리스트 조회 API 404 에러 기본값 설정

- public/svg/ic_arrow_right_16.svg
- src/assets/svgs/IcArrowRight16.tsx
- src/assets/svgs/index.ts
- src/pages/home/page/HomePage/HomePage.css.ts
- src/pages/home/page/HomePage/HomePage.tsx
- Closes #195
---
---
1. 메인페이지 누락된 '전체보기' 버튼 추가
---
-
---
> [Fix/#195] 메인페이지 누락된 '전체보기' 버튼 추가

- src/components/common/BottomSheet/BottomSheet.css.ts
- src/pages/view/components/MapBottomSheet/MapBottomSheet.css.ts
- src/pages/view/components/MapBottomSheet/MapBottomSheet.tsx
- src/pages/view/components/SelectStationModal/SelectStationModal.css.ts
- Closes #194
---
---
1. 지도 뷰 퍼블리싱 오류 수정
---
-
---
> [Fix/#194] 지도 뷰 퍼블리싱 오류 수정

- src/apis/home/useFetchCakeRank.ts
- src/apis/home/useFetchStoreRank.ts
- src/apis/instance.ts
- src/apis/myPage/useFetchUser.ts
- src/pages/store/components/Banner/Banner.tsx
- src/pages/store/components/StoreMenu/StoreMenu.css.ts
- src/types/apis/store/index.ts
- Closes #199
---
---
1. 인기 스토어 / 케이크 조회 404 에러 처리
2. 스토어 상세 페이지 count 수정
3. 스토어 상세보기 맛 white-space 처리
---
-
---
> [Feat/#199] 인기 스토어 / 케이크 조회 404 에러 처리

- src/components/common/Tab/Tab.css.ts
- src/components/common/Tab/Tab.tsx
- Closes #207
---
---
1. Tab 인터랙션 구현
---
-
---
> [Feat/#207] Tab 인터랙션 구현

- src/apis/auth/useDeleteLogout.ts
- src/apis/auth/usePostKakaoLogin.ts
- src/apis/instance.ts
- src/types/apis/auth/index.ts
- src/utils/auth.ts
- Closes #211
---
---
1. iOS, Safari에서 로그인이 안되는 에러가 생김에 따라 로그인 로직을 수정했습니다.
---
-
---
> [Fix/#211] 로그인 로직 수정

- public/svg/ic_top.svg
- src/assets/svgs/IcTop.tsx
- src/assets/svgs/index.ts
- src/components/common/TextButton/TextButton.tsx
- src/components/common/TopButton/TopButton.css.ts
- src/components/common/TopButton/TopButton.tsx
- src/components/common/index.ts
- src/hooks/index.ts
- src/hooks/useScrollTop.ts
- src/pages/designList/page/DesignListPage/DesignListPage.tsx
- src/pages/myPage/page/MyList/LikeListPage.tsx
- src/routes/Layout/Layout.tsx
- Closes #213
---
---
1. 둘러보기 페이지에서 클릭 시 맨 위로 스크롤 되는 탑 버튼을 구현합니다.
---
-
---
> [Feat/#213] TopButton 구현

- src/pages/view/components/SelectStationModal/SelectStationModal.css.ts
- Closes #217
---
---
1. 지하철 역 선택 모달 스타일 수정
---
-
---
> [Fix/#217] 지하철 역 선택 모달 스타일 수정

- src/apis/likes/useDeleteStoreLikes.ts
- src/apis/likes/usePostStoreLikes.ts
- src/apis/view/useFetchLikesStoreCoordinate.ts
- src/pages/view/hooks/useKakaoMap.tsx
- Closes #220 
---
---
1. 찜 개수 변경 시 마커 반영 안되는 에러 해결
---
-
---
> [Fix/#220] 찜 개수 변경 시 마커 반영 안되는 에러 해결

- src/components/common/Toast/Toast.css.ts
- src/pages/view/hooks/useKakaoMap.tsx
- Closes #219 
---
---
1. toast 패딩 수정
2. 지도 level 수정
---
-
---
> [Fix/#219] 기획 & 디자인 QA 1차 수정

- src/pages/view/hooks/useKakaoMap.tsx
- Closes #224 
---
---
1. 지도 뷰 모달 에러 수정
---
-
---
> [Fix/#224] 지도뷰 모달 수정

- src/pages/view/components/SelectedStoreModal/SelectedStoreModal.tsx
- Closes #232 
---
---
1. 모달 버튼 사이즈를 상세보기 버튼 사이즈와 통일
- 기존 small text button 사이즈이던 모달 버튼 사이즈를 large로 변경하여 사이즈 통일
---
> [Feat/#232] 모달 버튼 사이즈 변경
